### ISSUE TITLE
First half second not played?

### ISSUE THREAD

**Issue by Romkabouter** [koenvervloesem/hermes-audio-server#4]
Hey Koen, 

Thanks for this code! I am using it now connected to my Pi3+ and speaker to act as remote speaker. Works great, but.....
I have the sentence: Dat is goed, ik open het voorste rolluik, which is played correctly via the direct sound on Home Assistant instance. The cached file also contains the whole audio.

When I let audio-player do it's work however, only: "goed, ik open het voorste rolluik" is played.
I have tested it on a clean raspbian install. Any clues?

**Comment by koenvervloesem** [comment]
Hi Paul, that's weird, I haven't seen this behaviour. Does this happen with all audio? Could this have something to do with the characteristics of the audio? Sample width, number of channels, frame rate? You can see these characteristics when you start the audio player with the `--verbose` flag.

**Comment by Romkabouter** [comment]
Yes, happens with all audio:
Received an audio message of length 158.88 KiB with request id fa9d6faa-e756-4fdd-aac5-d234a08c2f74 on site matrixvoice.
Sample width: 2
Channels: 1
Frame rate: 44100
Finished playing audio message with id fa9d6faa-e756-4fdd-aac5-d234a08c2f74 on device default on site matrixvoice
I was using Rhasspy, but thought maybe it was Rhasspy.

What I did next was make a flow in node-red and inject the correct wave file directly into the playbytes topic. Same result.


Here is the node-red flow in case you want to try and reproduce the issue:
[{"id":"b1383638.151d08","type":"tab","label":"Flow 1","disabled":false,"info":""},{"id":"18f80853.bc3318","type":"mqtt out","z":"b1383638.151d08","name":"","topic":"hermes/audioServer/matrixvoice/playBytes/test","qos":"","retain":"","broker":"df4d2017.7afe1","x":610,"y":120,"wires":[]},{"id":"ddc6e1e6.f67cd","type":"inject","z":"b1383638.151d08","name":"","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":120,"y":120,"wires":[["d64e921b.37014"]]},{"id":"d64e921b.37014","type":"file in","z":"b1383638.151d08","name":"","filename":"/share/rhasspy/tts/googlewavenet/cache/dcdc7f5238dc1b893780029ed4f6832a.wav","format":"","chunk":false,"sendError":false,"encoding":"none","x":530,"y":120,"wires":[["18f80853.bc3318"]]},{"id":"df4d2017.7afe1","type":"mqtt-broker","z":"","name":"HA","broker":"192.168.43.169","port":"1883","clientid":"","usetls":false,"compatmode":true,"keepalive":"60","cleansession":true,"birthTopic":"","birthQos":"0","birthPayload":"","closeTopic":"","closeQos":"0","closePayload":"","willTopic":"","willQos":"0","willPayload":""}]

**Comment by koenvervloesem** [comment]
Weird. What audio hardware are you using? I have the ReSpeaker 2-Mics Pi HAT.

I see you have one channel. Does this also happen with stereo audio?

Does it also happen if you use `snips-audio-server` instead of `hermes-audio-server`?

**Comment by Romkabouter** [comment]
Google Wavenet only does mono output, I have a Raspberry Pi 3+ connected to TV via hdmi.
Clean install, with only hermes-audio-server installed. I will try snips as well, but have not installed it yet to keep the system as clean as possible. 

I think I might have found the cause, because a sound does not play at all.
Do you have VAD running on the playbytes as well?

Below output from the snips "hotword detected" soundbyte
Received an audio message of length 77.53 KiB with request id test on site matrixvoice.
Sample width: 2
Channels: 2
Frame rate: 44100
Finished playing audio message with id test on device default on site matrixvoice

Does not give any output to the speakers.

**Comment by koenvervloesem** [comment]
Sorry, I'm clueless, this has been working (also with the Snips hotword detected WAV file) for a week here. The audio player is very simple, no VAD: it just unpacks the WAV stream and plays them with PyAudio until there's no data in the stream left.

I'll investigate tomorrow if I can reproduce this with some other audio files.

**Comment by koenvervloesem** [comment]
I'm thinking: maybe it has something to do with the HDMI output? I haven't tested that...

**Comment by Romkabouter** [comment]
I have just switched to the Audio Jack, and this plays the soundbytes and the sentence completely.
Maybe there is some hardware issue of some sort, but I never had any issues before.

[edit] what you say indeed[/edit]

I don't know if it can be a software issue, you just use pyAudio right?

**Comment by koenvervloesem** [comment]
The code is just using PyAudio with the default audio output.

But thanks for trying this, I'll have a look into the issue later.
