### ISSUE TITLE
Stream wav file

### ISSUE THREAD

**Issue by Odianosen25** [koenvervloesem/hermes-audio-server#5]
Hello @koenvervloesem,

Thanks for your code.

Please I am working on a project, to stream a wav file to the ASR to transcribe it to text. The wav file has already been downloaded.

Please can you advise how I can use your code to do it? As since I can't select which device to use the recorder with, please help me with whatr i can use.

if your code can't do it, kindly point me in the right direction.

Kind regards

**Comment by koenvervloesem** [comment]
This is not possible with Hermes Audio Server. Are you using [Rhasspy](https://rhasspy.readthedocs.io/en/latest/)? Its API has an undocumented speech-to-text endpoint that transcribes WAV data to text. Just open http://IP_OF_RHASSPY:12101/api/ and search for `/api/speech-to-text`

**Comment by Odianosen25** [comment]
Hello @koenvervloesem,

Thanks for the response.

I am not presently using Rhasspy I am afraid, but just the Snips platform. So thought there was a way to stream a wav file, which the Snips ASR can be used to transcribe it.

So if I understand you, it will be possible to stream a stored wav file to Rhasspy over MQTT, and have it convert it to text?

I had written a little code (largely based on your work) which I think does stream my file over MQTT to the Snips ASR, but never got it to work. So if you saying Rhasspy can, I will give it a shot.

Kind regards
